
language: go
go:
  # - 1.9.x
  - 1.10.x
  - tip
# install:
#   - make dependency
script:
  - make test
matrix:
  allow_failures:
    include:
      - os: osx
      - os: linux
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  fast_finish: true

  notifications:
    email: true