# Golang CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/auyer/steganography
    steps:
      - checkout
      - run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
        file: coverage.txt
  test110:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/auyer/steganography
    steps:
      - checkout
      - run: go test -v ./...
  test19:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/auyer/steganography
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test110
      - test19
